### PR TITLE
Added Dark Violet color for dropdown

### PR DESCRIPTION
**Pull request by amanrk28**

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@amanrk28 The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by amanrk28** [comment]
> @amanrk28 The project structure is refactored please make changes accordingly and recommit them :) Thank You

@sakshamgurbhele  I've updated the code. Kindly check the PR. Thank You.

**Review by vishal-codes — APPROVED** [review]
Great work @amanrk28 Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by amanrk28** [comment]
> Great work @amanrk28 Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

Sure bro. Can you please add the hacktoberfest-connect tag to this PR?

**Pull request merged**
