### PR TITLE
feat: Added support for Arabic and Urdu

### PR DESCRIPTION
**Pull request by rehanpunjwani**
Added the support for Arabic and Urdu. (#3)

### CODE REVIEW

**Comment by vishal-codes** [comment]
> Added the support for Arabic and Urdu. (#3)

Great @rehanpunjwani  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by rehanpunjwani** [comment]
@vishal-codes can you please add the hacktoberfest-accepted label to this.

**Comment by vishal-codes** [comment]
> @vishal-codes can you please add the hacktoberfest-accepted label to this.

I m so sorry @rehanpunjwani I can't . But if u make a new pr with new changes I can add label to that. It's just that earlier I didn't had those labels but now I have so if u can make a new pr with new changes. LGTM🚀

**Comment by rehanpunjwani** [comment]
No problem. @vishal-codes  added a new pr #36

**Pull request merged**
