### PR TITLE
Added language

### PR DESCRIPTION
**Pull request by CyrusThapa11**
Added Turkish language . line 123 and 124 in Translate.js

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@copyNinja1219 The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
@copyNinja1219 the project **structure** is refactored, I can see that u have not updated upstream of ur forked version, please update it and then commit cganges

**Comment by vishal-codes** [comment]
@copyNinja1219 Ur branch is still behind. You can checkout [this comment](https://github.com/vishal-codes/react-widgets/pull/74#issuecomment-932940330) in which I have explained another contributor about how to update ur forked version of repository. Hope this might help :)

**Review by vishal-codes — CHANGES_REQUESTED** [review]
Please update ur repo it still has complex merge conflicts

**Review by vishal-codes — CHANGES_REQUESTED** [review]
@copyNinja1219 Ur branch is still behind. You can checkout [this comment](https://github.com/vishal-codes/react-widgets/pull/74#issuecomment-932940330) in which I have explained another contributor about how to update ur forked version of repository. Hope this might help :)

**Pull request closed without merging**
