### PR TITLE
Refactoring Project Structure

### PR DESCRIPTION
**Pull request by rizastoday**
So I'll try to help a bit by making some changes (based on #24) in folder structure to make this project little bit easier to maintain. Let me know if it has any issues
and sorry for my bad english :D

### CODE REVIEW

**Comment by vishal-codes** [comment]
> So I'll try to help a bit by making some changes (based on #24) in folder structure to make this project little bit easier to maintain. Let me know if it has any issues and sorry for my bad english :D

You really have done a great job @rizastoday , but I want the structure to be like `/src/components/pages/Accordion.js`  instead of `/src/components/pages/Accordion/index.js` , the same goes to other components as well. Can u please make this changes? 
also no need to apologize your english is not bad.

**Comment by rizastoday** [comment]
Hi @vishal-codes I've made some changes to recent commit, and I also moving translate page's array to separate data folder to make it easey and clear to maintain. This is how project structure look so far:

image

**Comment by vishal-codes** [comment]
Finally !! Yeaay Done resolving all the merge conflicts @rizastoday. Great work, Thank you so much. Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by rizastoday** [comment]
Woah thank you so much too @vishal-codes

**Pull request merged**
