### PR TITLE
Added Gujarati and Japanese

### PR DESCRIPTION
**Pull request by SanskritiKhatiyan**
Plzzz merge it.

### CODE REVIEW

**Comment by vishal-codes** [comment]
> Plzzz merge it.

Yaa sure. Great work @SanskritiKhatiyan  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by vishal-codes** [comment]
@sakshamgurbhele merge and label

**Comment by sakshamgurbhele** [comment]
@vishal-codes There is a conflict with:  src/components/Translate.js
Have a look

**Comment by vishal-codes** [comment]
> @vishal-codes There is a conflict with: src/components/Translate.js Have a look

Resolved the conflicts

**Review by sakshamgurbhele — APPROVED** [review]

**Comment by SanskritiKhatiyan** [comment]
@vishal-codes Thanks

**Comment by vishal-codes** [comment]
> @vishal-codes Hey why it is showing that this project is not participating in hacktober???

@sakshamgurbhele this project isn't participating in hacktoberfest ?

**Pull request merged**
