### PR TITLE
 Update : data's are updated

### PR DESCRIPTION
**Pull request by MOHAMMEDAFEEF**
* react warnings are resolved
* 4 colors are added
* 4 colors are added

### CODE REVIEW

**Review by vishal-codes — CHANGES_REQUESTED** [review]
@MOHAMMEDAFEEF u haven't added the colors and language in alphabetical order please arrange them and also replace  `"`  with  `' `  also what kind of change u maide in `src/components/base/Convert.js`

**Comment by MOHAMMEDAFEEF** [comment]
@vishal-codes changed != to !== for removing the react warning

**Comment by MOHAMMEDAFEEF** [comment]
@vishal-codes color ( SandyBrown, PaleVioletRed, NavajoWhite, Khaki ) and language ( Latvian, Khmer, Igbo, Hausa ) arranged in alphabetical order and also replaced `"` with `'`

**Comment by vishal-codes** [comment]
Great work @MOHAMMEDAFEEF  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)   <br> @sakshamgurbhele can u  please label this pr and merge it

**Review by vishal-codes — APPROVED** [review]

**Review by sakshamgurbhele — APPROVED** [review]

**Pull request merged**
