### PR TITLE
Added Purple and Voilet color

### PR DESCRIPTION
**Pull request by aabhijeet011**
#1 
I Have Added the Purple and Voilet color as documented. Please take a review and merge it.

### CODE REVIEW

**Review by vishal-codes — CHANGES_REQUESTED** [review]
Its not Voilet , its Violet

**Comment by sakshamgurbhele** [comment]
@aabhijeet011 The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
should I close this pr @aabhijeet011 ?

**Comment by aabhijeet011** [comment]
> should I close this pr @aabhijeet011 ?

Yes sure, I have created a new PR due to conflicting in this PR.....Please see PR #107 and merge it.

**Pull request closed without merging**
