### PR TITLE
Added Malayalam and Tamil under Languages

### PR DESCRIPTION
**Pull request by AkshayHere**

### CODE REVIEW

**Comment by vishal-codes** [comment]
Great @AkshayHere  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by vishal-codes** [comment]
@sakshamgurbhele  please label this pr and merge it

**Review by sakshamgurbhele — APPROVED** [review]

**Comment by sakshamgurbhele** [comment]
@vishal-codes again conflict with : src/components/Translate.js

**Comment by sakshamgurbhele** [comment]
Cool 👍🏼

**Comment by vishal-codes** [comment]
@sakshamgurbhele  Just done resolving the conflicts for this branch can u please label this pr and merge it.

**Review by sakshamgurbhele — APPROVED** [review]

**Comment by AkshayHere** [comment]
> 
> 
> Great @AkshayHere Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

Thanks vishal. Happy too Contribute :)

**Pull request merged**
