### PR TITLE
added color

### PR DESCRIPTION
**Pull request by 2201monesh**
added Crimson color

### CODE REVIEW

**Comment by 2201monesh** [comment]
can you give this a hacktoberfest label

**Comment by sakshamgurbhele** [comment]
@2201monesh dw, we will do it

**Review by vishal-codes — CHANGES_REQUESTED** [review]
Please add the color in alphabetical order as mentioned in the issue

**Comment by 2201monesh** [comment]
@vishal-codes okay sure

**Comment by 2201monesh** [comment]
Hey @vishal-codes I have raised a new PR with the suggested changes have a look at #88

**Pull request closed without merging**
