### PR TITLE
Added new color Chocolate

### PR DESCRIPTION
**Pull request by lalit-commits**
Added new color Chocolate

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@lalit-commits The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
@lalit-commits 
the project structure is refactored, Check the deployed website the project is also updated. Your forked version is behind so please update and make commits again. The changes u have done are absolutely correct but the branch is having complex merge conflicts. So can u please update it also Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by vishal-codes** [comment]
@lalit-commits Ur branch is still behind. You can checkout [this comment](https://github.com/vishal-codes/react-widgets/pull/74#issuecomment-932940330) in which I have explained another contributor about how to update ur forked version of repository. Hope this might help :)

**Comment by vishal-codes** [comment]
@lalit-commits chocolate color is already added, if u want u can add another color and make commits again

**Pull request closed without merging**
