### PR TITLE
feat: add DarkSalmon color to dropdown options

### PR DESCRIPTION
**Pull request by arthur322**
Adds DarkSalmon color to dropdown options. #1

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@arthur322 The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
@arthur322  the project structure is refactored, Check the deployed website the project is also updated. Your forked version is behind so please update and make commits again. The changes u have done are absolutely correct but the branch is having complex merge conflicts. So can u please update it also Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by arthur322** [comment]
Ok! Sure!

**Comment by vishal-codes** [comment]
> Ok! Sure!

@arthur322 I have resolved ur merge conflicts. The project is refactored this means that u gotta make changes in another folder. Please check the respective issue I have updated guidelines for changes to be done in which folder :)

**Comment by arthur322** [comment]
Thanks @vishal-codes, now the PR has the correct code :) thanks for the merge!

**Review by sakshamgurbhele — APPROVED** [review]
LGTM

**Pull request merged**
