### PR TITLE
Added DarkOrange and DarkOliveGreen colors

### LINKED ISSUE #1: Add more colors in dropdown section
As of now the Dropdown section of the project only supports two colors (Blue and Yellow). We can add more colours.
Before making changes please make sure that you have completed steps till [Branching](https://github.com/vishal-codes/react-widgets/blob/main/CONTRIBUTING.md#branching).

#### Steps for adding more colours 
1.  change the directory from present to the `src/data/colorOptions.js` file.
2. now edit the array named [colorOptions ](https://github.com/vishal-codes/react-widgets/blob/886ff877c86985311fadfcb2626f6146252bfa38/src/data/colorOptions.js#L1) by adding a new item and assign the `label` and `value` with the colour name (please follow the casing)
3. save the changes and [commit](https://github.com/vishal-codes/react-widgets/blob/main/CONTRIBUTING.md#commiting-changes)

#### List of colour's to be added (NOTE: You don't need to add all the colours, just add one or two colour's. Not more than two.)
- [x] AntiqueWhite
- [x] Aqua
- [x] Aquamarine
- [x] Blue
- [x] BlueViolet
- [x] Brown
- [x] CadetBlue
- [x] Chartreuse
- [x] Chocolate
- [x] Coral
- [x] CornflowerBlue
- [x] Crimson
- [x] Cyan
- [x] DarkBlue
- [x] DarkCyan
- [x] DarkGoldenRed
- [x] DarkGray
- [x] DarkGreen
- [x] DarkKhaki
- [x] DarkMagenta
- [x] DarkOliveGreen
- [x] DarkOrange
- [x] DarkOrchid
- [x] DarkRed
- [x] DarkTurquoise
- [x] DarkViolet
- [x] DeepPink
- [ ] DeepSkyBlue
- [x] DimGray
- [ ] DodgerBlue
- [ ] ForestGreen
- [x] Fuchsia
- [x] Gold
- [x] Green
- [ ] GreenYellow
- [x] HotPink
- [ ] IndianRed 
- [ ] Indigo 
- [x] Khaki
- [x] Lavender
- [x] LightBlue
- [x] LightCoral
- [ ] LightGreen
- [x] LightPink
- [x] LightSalmon
- [x] LightSeaGreen
- [x] Lime
- [ ] Linen
- [ ] Magenta
- [x] Maroon
- [ ] MediumBlue
- [ ] MidnightBlue
- [x] NavajoWhite
- [x] Olive
- [x] OrangeRed
- [x] Orchid
- [x] PaleGreen
- [x] PaleVioletRed
- [x] Peru
- [x] Pink
- [x] Plum
- [x] Purple
- [x] Red
- [x] SandyBrown
- [ ] Silver
- [ ] Snow
- [x] Tomato
- [ ] Turquoise
- [x] Violet
- [ ] WhiteSmoke
- [x] Yellow
- [ ] YellowGreen

### PR DESCRIPTION
**Pull request by Atharv777**
I have added DarkOrange and DarkOliveGreen colors in the color dropdown. fixes #1

### CODE REVIEW

**Review by MukulKolpe — DISMISSED** [review]
LGTM👍

**Comment by sakshamgurbhele** [comment]
@Atharv777 The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
@Atharv777  the project structure is refactored, Check the deployed website the project is also updated. Your forked version is behind so please update and make commits again. The changes u have done are absolutely correct but the branch is having complex merge conflicts. So can u please update it also Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by Atharv777** [comment]
@vishal-codes please tell me how to solve this merge conflict.

**Comment by vishal-codes** [comment]
> @vishal-codes please tell me how to solve this merge conflict.

@Atharv777  Checkout the `Fetch upstream` button on page of ur forked version. Then click on `Fetch and merge` . Then go on ur terminal and enter `git pull` then  do the changes which u want and push again.
InkedScreenshot 2021-10-03 130944_LI

**Comment by Atharv777** [comment]
Thanks @vishal-codes. May I move this down to make it alphabetically ordered?
Screenshot (298)

**Comment by Atharv777** [comment]
I am sorry @vishal-codes I am closing this PR and starting everything from starting.

**Comment by Atharv777** [comment]
Now please check and merge my new PR #109

**Pull request closed without merging**
