### PR TITLE
Refactor: Make debouncing generic

### PR DESCRIPTION
**Pull request by shoryakaushik**
Updates Search Component by making debouncing generic so that it can be used anywhere across app without repeating the code.

### CODE REVIEW

**Comment by shoryakaushik** [comment]
@vishal-codes can you review this? Just solved some conflicts.

**Comment by vishal-codes** [comment]
> @vishal-codes can you review this? Just solved some conflicts.

@shoryakaushik the project structure is refactored. Can u please make the changes accordingly and recommit changes again coz the deployment tests have failed.

**Comment by shoryakaushik** [comment]
> > @vishal-codes can you review this? Just solved some conflicts.
> 
> @shoryakaushik the project structure is refactored. Can u please make the changes accordingly and recommit changes again coz the deployment tests have failed.

**Comment by shoryakaushik** [comment]
@vishal-codes updated

**Comment by vishal-codes** [comment]
Great work @shoryakaushik , Thank you for ur contributions. Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Pull request merged**
