### PR TITLE
Add nordic languages

### PR DESCRIPTION
**Pull request by iMeriem**
**Added :**
Noewegian
Swedich
Danish
Finnish

### CODE REVIEW

**Comment by vishal-codes** [comment]
> **Added :** Noewegian Swedich Danish Finnish

Hey @iMeriem there have been some changes in the package-lock.json file can u please undo those ?

**Comment by iMeriem** [comment]
Yes, sure @vishal-codes

**Comment by vishal-codes** [comment]
@iMeriem the project structure is refactored please make the changes accordingly :)

**Comment by vishal-codes** [comment]
@iMeriem Please update ur forked version and then commit changes :)

**Comment by vishal-codes** [comment]
@iMeriem Ur branch is still behind. You can checkout [this comment](https://github.com/vishal-codes/react-widgets/pull/74#issuecomment-932940330) in which I have explained another contributor about how to update ur forked version of repository. Hope this might help :)

**Pull request closed without merging**
