### PR TITLE
chore: adding portuguese language

### PR DESCRIPTION
**Pull request by sauloviniciusf**

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@sauloviniciusf The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
@sauloviniciusf the project structure is refactored, Check the deployed website the project is also updated. Your forked version is behind so please update and make commits again. The changes u have done are absolutely correct but the branch is having complex merge conflicts. So can u please update it also Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by vishal-codes** [comment]
@sauloviniciusf Ur branch is still behind. You can checkout [this comment](https://github.com/vishal-codes/react-widgets/pull/74#issuecomment-932940330) in which I have explained another contributor about how to update ur forked version of repository. Hope this might help :)

**Comment by sauloviniciusf** [comment]
@vishal-codes now it's ok

**Comment by vishal-codes** [comment]
> @vishal-codes now it's ok

Great work @sauloviniciusf  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Pull request merged**
