### PR TITLE
Added coral color

### PR DESCRIPTION
**Pull request by mrerror403**
Added coral color

### CODE REVIEW

**Review by sakshamgurbhele — COMMENTED** [review]
Looks good

**Comment by mrerror403** [comment]
> Looks good

**Comment by mrerror403** [comment]
@sakshamgurbhele please merge the pull request

**Review by vishal-codes — APPROVED** [review]
Great work @mrerror403  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by vishal-codes** [comment]
@sakshamgurbhele can u please label this pr and merge it

**Comment by vishal-codes** [comment]
Coral is already added @mrerror403

**Pull request closed without merging**
