### PR TITLE
add color Silver to dropdown options

### PR DESCRIPTION
**Pull request by gefymarcos**
Adds Silver color to dropdown options

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@gefymarcos The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by vishal-codes** [comment]
@gefymarcos the project structure is refactored, Check the deployed website the project is also updated. Your forked version is behind so please update and make commits again. The changes u have done are absolutely correct but the branch is having complex merge conflicts. So can u please update it also Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Review by vishal-codes — CHANGES_REQUESTED** [review]
Color's should be added in alphabetical order.

**Comment by vishal-codes** [comment]
@gefymarcos I have resolved ur merge conflicts. The project is refactored this means that u gotta make changes in another folder. Please check the respective issue I have updated guidelines for changes to be done in which folder :) Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Review by sakshamgurbhele — APPROVED** [review]
LGTM

**Review by vishal-codes — APPROVED** [review]

**Pull request merged**
