### PR TITLE
added languages Amharic and Armenian

### PR DESCRIPTION
**Pull request by abhishekgupta23**

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@abhishekgupta23 The project structure is refactored please make changes accordingly and recommit them :) Thank You

**Comment by abhishekgupta23** [comment]
Sir i have made changes, Please check.

**Review by sakshamgurbhele — APPROVED** [review]

**Comment by abhishekgupta23** [comment]
hi,
can you please tell why you have marked my request as invalid

**Comment by abhishekgupta23** [comment]
> hi, can you please tell why you have marked my request as invalid

sir in the readme file it was written that we can add languages to the project
and i have just added two languages in the same way others are added

**Comment by abhishekgupta23** [comment]
sir please give me hacktoberfest accepted label or please remove the invalid label
please sir.

**Pull request merged**
