### PR TITLE
TextUtils Widget Added 

### PR DESCRIPTION
**Pull request by shubhamjha25**
As per the things mentioned in #76, I have added the **TextUtils** Widget.
TextUtils Gives You A Way To Analyze Your Text Quickly And Efficiently.
The main remains Dark and the text colors are white accordingly.

Screenshot for Reference:
TextUtils Done
It would be great if you consider this and merge the pr.
Thank You!

### CODE REVIEW

**Comment by vishal-codes** [comment]
Great work @shubhamjha25 but the project structure is refactored and also ur branch has complex conflicts, can u make changes according and recommit changes

**Comment by shubhamjha25** [comment]
Yeah, the conflicts came up when the project structure was refactored. 
At the time of making this pr (#92), there were no conflicts.

Let me do some rearrangement.
Will send a new PR soon.

**Comment by shubhamjha25** [comment]
Hey @vishal-codes, I guess its working fine now.
Can you please check!

**Comment by vishal-codes** [comment]
Great work @shubhamjha25 . Thank You for your amazing contributions. Would love to get connected with you on twitter. Here's my handle [@vishaltwts](https://twitter.com/vishaltwts) :)

**Comment by shubhamjha25** [comment]
Thanks for merging! 🥳
You may close #76 now. 😄

**Pull request merged**
