### PR TITLE
Added colour Antique White in app

### PR DESCRIPTION
**Pull request by tekbones**
PR as part of Hacktober 2021

### CODE REVIEW

**Review by vishal-codes — CHANGES_REQUESTED** [review]
Its 'AntiqueWhite and not 'Antique White' . No need to give space. Now first pull the changes from remote main and then do changes and then commit. All the best :)

**Review by tekbones — COMMENTED** [review]
Changes made! Thank you!

**Review by vishal-codes — APPROVED** [review]
Great

**Comment by vishal-codes** [comment]
Great @tekbones  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Pull request merged**
