### PR TITLE
Added DeepPink color

### PR DESCRIPTION
**Pull request by hellodeborahuk**
VS Code automatically changed all ' to ".

### CODE REVIEW

**Comment by vishal-codes** [comment]
> VS Code automatically changed all ' to ".

No worries I changed them back.

**Comment by vishal-codes** [comment]
> I've changed to DeepPink as I noticed someone else working on the same color, just working out how to submit that.

Yes ThankYou, Great work @hellodeborahuk  Do consider connecting with me on twitter [@vishaltwts](https://twitter.com/vishaltwts) :)

**Review by sakshamgurbhele — APPROVED** [review]

**Comment by vishal-codes** [comment]
@sakshamgurbhele can u please label this pr and merge it

**Comment by hellodeborahuk** [comment]
Thank you, following on Twitter.

**Pull request merged**
