### PR TITLE
Added Aquamarine color

### PR DESCRIPTION
**Pull request by parthn2**

### CODE REVIEW

**Review by vishal-codes — CHANGES_REQUESTED** [review]
Please add the color in alphabetical order as requested :)

**Comment by parthn2** [comment]
> Please add the color in alphabetical order as requested :)

The last color added was 'aqua' by some person so added the next one! I would change it surely

**Comment by parthn2** [comment]
> Please add the color in alphabetical order as requested :)

I hope I have done it correct now! :)

**Review by vishal-codes — APPROVED** [review]

**Comment by vishal-codes** [comment]
@sakshamgurbhele please add label and merge this pr

**Pull request merged**
